databases:
  - name: royal_leaguedb # Puedes cambiar el nombre de la base de datos si quieres
    plan: free
    databaseName: royal_league # Este será el nombre de la DB en Render
    user: royal_league_user # Este será el usuario de la DB en Render

services:
  - type: web
    plan: free
    name: royal-league-app
    runtime: python
    buildCommand: 'pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata initial_data.json'
    startCommand: 'python -m gunicorn royal_league.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: royal_leaguedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4