# Generated by Django 5.1.6 on 2025-06-09 11:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=7)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('nation_text', models.CharField(blank=True, max_length=255, null=True)),
                ('nation_image', models.URLField(blank=True, null=True)),
                ('position', models.JSONField(default=list, null=True)),
                ('value_million', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('current_team_text', models.CharField(blank=True, max_length=255, null=True)),
                ('current_team_image', models.URLField(blank=True, null=True)),
                ('past_teams', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royal_app.player')),
            ],
        ),
    ]
